### ISSUE TITLE
Trigger PR build only on updates to specific directories

### ISSUE THREAD

**Issue by smashwilson** [deconst/strider-deconst-content#22]
> Several API doc projects are integrated into developer repos, like Autoscale. One of the Autoscale devs asked whether the PR builder webhook can be customized so that it only builds when a PR contains changes in the docs source directory.

Moved from rackerlabs/nexus-control#369.

**Comment by smashwilson** [comment]
We'll get this one for free with deconst/deconst-docs#234. If there are no changed envelopes to upload, then I can omit the preview comment. :sparkles:

**Comment by smashwilson** [comment]
If no envelopes have actually changed in a PR build, the build plugin will not submit anything to the staging content service and won't post a preview comment. :tada:

Although I've fixed all of the ones that I'm aware of, there may still be situations that cause the submitter to think that envelopes have changed when they haven't. @manishtomar, if you still see preview links on any non-docs otter PRs, can you @-mention me so I can investigate?

**Comment by manishtomar** [comment]
> @manishtomar, if you still see preview links on any non-docs otter PRs, can you @-mention me so I can investigate?

@smashwilson Sure. Will do.

**Comment by manishtomar** [comment]
@smashwilson This is still happening. See https://github.com/rackerlabs/otter/pull/1887 and https://github.com/rackerlabs/otter/pull/1890.
